services:
  unbound:
    image: unbound
    volumes:
      - ./unbound/:/unbound
    hostname: unbound
    ports:
      - 53:53
      - "53:53/udp"
      - 853:853
      - 8953:8953
    environment:
    deploy:
      restart_policy:
        condition: on-failure
      placement:
